// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ServiceStatus {
    /**
     * Creates a new ServiceStatus instance.
     * @param {Partial<ServiceStatus>} [$$source = {}] - The source object to create the ServiceStatus.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("is_healthy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_healthy"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceStatus(/** @type {Partial<ServiceStatus>} */($$parsedSource));
    }
}
