// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * @returns {$CancellablePromise<domain$0.ServiceStatus>}
 */
export function GetServiceStatus() {
    return $Call.ByID(4058905530).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(options) {
    return $Call.ByID(4054507023, options);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3110497941);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function WatchLogs(filePath) {
    return $Call.ByID(927011949, filePath);
}

// Private type creation functions
const $$createType0 = domain$0.ServiceStatus.createFrom;
