// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * @returns {$CancellablePromise<domain$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(1921182139).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(options) {
    return $Call.ByID(4054507023, options);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RestartService(id) {
    return $Call.ByID(1495361373, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3110497941);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartService(id) {
    return $Call.ByID(3856488036, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopService(id) {
    return $Call.ByID(645239674, id);
}

// Private type creation functions
const $$createType0 = domain$0.Config.createFrom;
