// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServiceStatus() {
  return window['go']['app']['App']['GetServiceStatus']();
}

export function WatchLogs(arg1) {
  return window['go']['app']['App']['WatchLogs'](arg1);
}
