// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetServiceStatus():Promise<domain.ServiceStatus>;

export function WatchLogs(arg1:string):Promise<void>;
